---
- name: Install MySQL server
  hosts: mysql-server
  become: true
  tasks:
    - name: Install MySQL server
      ansible.builtin.apt:
        name: mysql-server
        update_cache: true

    - name: Start MySQL server
      ansible.builtin.service:
        name: mysql
        state: restarted
        enabled: true
